name: Deploy Frontend and Backend to EC2

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /home/ubuntu/edutrack-learning
            git pull origin main

            npm install

            # Membuat file .env
            cat > .env << EENV
$ENV_FILE
EENV

            npm run build
            
            sudo cp -r dist/* /var/www/html/
          EOF
