# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: edutrack-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./src
    container_name: edutrack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
