version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # host:container
      - "80:80"
    env_file:
      - .env
    restart: always

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   env_file:
  #     - .env
  #   restart: always