version: '3.8'
services:
  backend:
    container_name: edutrack-learning-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    container_name: edutrack-learning-frontend
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
