version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: edutrack-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - edutrack-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: edutrack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - edutrack-net

networks:
  edutrack-net:
    driver: bridge
